@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

EzFoodie *-right-> "1" UniqueMemberList
EzFoodie *-right-> "1" UniqueReservationList
UniqueReservationList -[hidden]down- UniqueMemberList
UniqueReservationList -[hidden]down- UniqueMemberList

UniqueReservationList *-right-> "*" Reservation
UniqueMemberList -right-> Member

Member -up-> "*" Reservation

Member *--> Name
Member *--> Phone
Member *--> Email
Member *--> Address
@enduml
