@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EzFoodieParser" as EzFoodieParser LOGIC_COLOR

participant ":DeleteCommandPrefixParser" as DeleteCommandPrefixParser LOGIC_COLOR
participant ":DeleteMemberCommandParser" as DeleteMemberCommandParser LOGIC_COLOR
participant "command:DeleteMemberCommand" as DeleteMemberCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("del -mem/ -i/1")
activate LogicManager

LogicManager -> EzFoodieParser : parseCommand("del -mem/ -i/1")
activate EzFoodieParser

create DeleteCommandPrefixParser
EzFoodieParser -> DeleteCommandPrefixParser : DeleteCommandPrefixParser()
activate DeleteCommandPrefixParser

DeleteCommandPrefixParser --> EzFoodieParser
deactivate DeleteCommandPrefixParser

EzFoodieParser -> DeleteCommandPrefixParser : parse(" -mem/ -i/1")
activate DeleteCommandPrefixParser

create DeleteMemberCommandParser
DeleteCommandPrefixParser -> DeleteMemberCommandParser : DeleteMemberCommandParser()
activate DeleteMemberCommandParser

DeleteMemberCommandParser --> DeleteCommandPrefixParser
deactivate DeleteMemberCommandParser

DeleteCommandPrefixParser --> EzFoodieParser
deactivate DeleteCommandPrefixParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandPrefixParser -[hidden]-> EzFoodieParser
destroy DeleteCommandPrefixParser

EzFoodieParser -> DeleteMemberCommandParser : parse(" -mem/ -i/1")
activate DeleteMemberCommandParser

create DeleteMemberCommand
DeleteMemberCommandParser -> DeleteMemberCommand : DeleteMemberCommand(1)
activate DeleteMemberCommand

DeleteMemberCommand --> DeleteMemberCommandParser : command
deactivate DeleteMemberCommand

DeleteMemberCommandParser --> EzFoodieParser : command
deactivate DeleteMemberCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteMemberCommandParser -[hidden]-> EzFoodieParser
destroy DeleteMemberCommandParser

EzFoodieParser --> LogicManager : command
deactivate EzFoodieParser

LogicManager -> DeleteMemberCommand : execute(model)
activate DeleteMemberCommand

DeleteMemberCommand -> Model : getFilteredPatientList()
activate Model

Model --> DeleteMemberCommand : lastShownList
deactivate Model

DeleteMemberCommand -> Model : deleteMember(memberToDelete)
activate Model

Model --> DeleteMemberCommand
deactivate Model

create CommandResult
DeleteMemberCommand -> CommandResult : CommandResult(message)
activate CommandResult

CommandResult --> DeleteMemberCommand
deactivate CommandResult

DeleteMemberCommand --> LogicManager : result
deactivate DeleteMemberCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteMemberCommand -[hidden]-> LogicManager
destroy DeleteMemberCommand

[<--LogicManager
deactivate LogicManager
@enduml
