@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class EzFoodieParser
Class UVWXYZCommand
Class UVWCommand
Class CommandResult
Class "{abstract}\nCommand" as Command


Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" EzFoodieParser
EzFoodieParser ..> UVWXYZCommand : creates >
EzFoodieParser ..> UVWCommand : creates >

UVWXYZCommand -up-|> Command
UVWCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of UVWXYZCommand: UVW = Add, Edit, etc \nXYZ = Member, Transaction, etc \nUVWXYZCommand = AddMemberCommand, \nEditTransactionCommand, etc
note right of UVWCommand: UVWCommand = FindCommand, \nShowCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
