@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyEzFoodie <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class EzFoodie
Class ReadOnlyEzFoodie
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueMemberList
Class Member
Class Address
Class Email
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

EzFoodie .up.|> ReadOnlyEzFoodie

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyEzFoodie
ModelManager -left-> "1" EzFoodie
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

EzFoodie *--> "1" UniqueMemberList
UniqueMemberList --> "~* all" Member
Member *--> Name
Member *--> Phone
Member *--> Email
Member *--> Address
Member *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Member
@enduml
