@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "Account Storage" #F4F6F6{
Interface AccountStorage <<Interface>>
Class JsonAccountStorage
}

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "EzFoodie Storage" #F4F6F6{
Interface EzFoodieStorage <<Interface>>
Class JsonEzFoodieStorage
Class JsonSerializableEzFoodie
Class JsonAdaptedMember
Class JsonAdaptedTransaction
Class JsonAdaptedReservation
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage

StorageManager -up-> "1" AccountStorage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" EzFoodieStorage

Storage -left-|> AccountStorage
Storage -left-|> UserPrefsStorage
Storage -right-|> EzFoodieStorage

JsonAccountStorage .up.|> AccountStorage
JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonEzFoodieStorage .up.|> EzFoodieStorage

JsonEzFoodieStorage ..> JsonSerializableEzFoodie
JsonSerializableEzFoodie --> "*" JsonAdaptedMember
JsonAdaptedMember --> "*" JsonAdaptedTransaction
JsonAdaptedMember --> "*" JsonAdaptedReservation

@enduml
