@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EzFoodieParser" as EzFoodieParser LOGIC_COLOR
participant "command:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedEzFoodie" as VersionedEzFoodie MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> EzFoodieParser : parseCommand("undo")
activate EzFoodieParser

create UndoCommand
EzFoodieParser -> UndoCommand
activate UndoCommand

UndoCommand --> EzFoodieParser : command
deactivate UndoCommand

EzFoodieParser --> LogicManager : command
deactivate EzFoodieParser

LogicManager -> UndoCommand : execute(model)
activate UndoCommand

UndoCommand -> Model : undoEzFoodie()
activate Model

Model -> VersionedEzFoodie : undo()
activate VersionedEzFoodie

VersionedEzFoodie -> VersionedEzFoodie :resetData(ReadOnlyEzFoodie)
VersionedEzFoodie --> Model :
deactivate VersionedEzFoodie

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
